db:
  image: mariadb:5.5
  environment:
  - MYSQL_DATABASE=satnogsdb
  - MYSQL_USER=satnogsdb
  - MYSQL_PASSWORD=satnogsdb
  - MYSQL_ROOT_PASSWORD=toor
redis:
  image: redis:3.2.8
web:
  build: .
  ports:
    - "8000:8000"
  volumes:
    - .:/app
  links:
    - db
    - redis
  environment:
    - DJANGO_SETTINGS_MODULE=db.settings.docker
    - DEFAULT_FROM_EMAIL=noreply@example.com
    - ALLOWED_HOSTS=*
    - DATABASE_URL=mysql://satnogsdb:satnogsdb@db/satnogsdb
  command:
    ./docker/run-docker.sh
